# Generated by Django 5.0.3 on 2024-03-31 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_cart',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_product',
            field=models.ForeignKey(db_column='id_product', default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number_of_product',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='history',
            name='id_history',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id_product',
            field=models.ForeignKey(db_column='id_product', default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='history',
            name='number_of_product',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
