# Generated by Django 5.0.3 on 2024-03-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cart_id_cart_alter_cart_id_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.IntegerField(default=2),
        ),
    ]
