# Generated by Django 5.0.3 on 2024-04-08 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
