# Generated by Django 5.0.3 on 2024-04-08 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_history_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id_history',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
    ]
