# Generated by Django 5.0.3 on 2024-04-15 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_history_id_history_alter_history_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2024, 4, 16)),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=20),
        ),
    ]
