# Generated by Django 5.0.3 on 2024-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_history_purchase_date_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='khach_hang', max_length=20),
        ),
    ]
