# Generated by Django 5.0.3 on 2024-04-25 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
    ]
